### ISSUE TITLE
FlexFlow Serve development plan

### ISSUE THREAD

**Issue by goliaro** [flexflow/flexflow-serve#38]
This issue tracks our progress on FlexFlow Serve issues and TODOs

## Features

- [ ] CFG: flexflow/flexflow-serve#39 
- [ ] Change generation parameters after compile flexflow/flexflow-serve#36 

## Models

- [ ] other LLM/SSMs flexflow/flexflow-serve#22

## Performance

- [ ] Saving model weights in a single file flexflow/flexflow-serve#42 

## AMD Support

- [ ] hipcub library compile issue flexflow/flexflow-serve#23 

## Completed
- [x] Object returned by `llm.generate` flexflow/flexflow-serve#63 
- [x] LLaMA-2-70b mismatch flexflow/flexflow-serve#56 
- [x] `pip install` can run into some issues sometimes flexflow/flexflow-serve#80 
- [x] AMD Support: flexflow/flexflow-train#996 
- [x] Async API: flexflow/flexflow-serve#24 
- [x] Support for models stored locally flexflow/flexflow-serve#64 
- [x] Specify batch size and related parameters without need to recompile FlexFlow flexflow/flexflow-serve#67 
- [x] Generate EOS token automatically flexflow/flexflow-serve#62
- [x] Prompt templates for chat flexflow/flexflow-serve#79 
- [x] Add support for MPT family of models flexflow/flexflow-serve#60
